export const E2E_POSTGRES_PORT = '25432';
export const E2E_MINIO_PORT = '29000';
export const E2E_MINIO_CONSOLE_PORT = '29001';
export const E2E_SERVER_PORT = '28080';
export const E2E_WEB_PORT = '25173';
export const E2E_BASE_URL = `http://127.0.0.1:${E2E_WEB_PORT}`;

export const E2E_COMPOSE_ENV = {
  POSTGRES_PORT: E2E_POSTGRES_PORT,
  MINIO_PORT: E2E_MINIO_PORT,
  MINIO_CONSOLE_PORT: E2E_MINIO_CONSOLE_PORT,
  SERVER_PORT: E2E_SERVER_PORT,
  WEB_PORT: E2E_WEB_PORT,
  PUBLIC_BASE_URL: E2E_BASE_URL,
  CORS_ORIGINS: E2E_BASE_URL,
} as const;
