/**
 * Codegen `CLI_VERSION` from `apps/cli/package.json`.
 *
 * Mirrors the pattern used by `packages/kernel/scripts/gen-version.ts`:
 * generated file is committed to git so sibling packages can import
 * `CLI_VERSION` at dev time without a pre-build, and re-emitted by
 * `prebuild` so `dist/` is always in sync with the package manifest.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.join(here, '..', 'package.json');
const outPath = path.join(here, '..', 'src', 'version.ts');

const pkgJson = JSON.parse(readFileSync(pkgPath, 'utf8')) as { readonly version: string };

const content = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit.
export const CLI_VERSION = '${pkgJson.version}' as const;
`;

writeFileSync(outPath, content);
