/**
 * Codegen the kernel's version constants from package manifests.
 *
 * Emits:
 *
 * - `KERNEL_VERSION`       — the `@cad/kernel` package version (from our own `package.json`)
 * - `OCCT_PACKAGE_VERSION` — the `replicad-opencascadejs` package version we depend on
 *
 * Both constants are synchronous exports so consumers (e.g. `apps/cli`) can
 * surface version info without booting the OCCT WASM kernel. For the
 * run-time-queried OCCT C++ macro version, use `getOccVersion()` from
 * `src/occt.ts` — that requires a booted instance.
 *
 * Runs as `prebuild` so `dist/` is always in sync with the package manifest.
 * The generated `src/version.ts` is committed to git — siblings in the
 * monorepo (tests, apps/cli, apps/web) can import it directly at dev time
 * without a pre-compile step.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const kernelPkgPath = path.join(here, '..', 'package.json');
const outPath = path.join(here, '..', 'src', 'version.ts');

const require = createRequire(import.meta.url);
const occtPkgPath = require.resolve('replicad-opencascadejs/package.json');

const kernelPkg = JSON.parse(readFileSync(kernelPkgPath, 'utf8')) as { readonly version: string };
const occtPkg = JSON.parse(readFileSync(occtPkgPath, 'utf8')) as { readonly version: string };

// Single-quoted to match the project's Prettier style.
const content = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit.
export const KERNEL_VERSION = '${kernelPkg.version}' as const;
export const OCCT_PACKAGE_VERSION = '${occtPkg.version}' as const;
`;

writeFileSync(outPath, content);
